### ISSUE TITLE
issue with Subword_Torch

### ISSUE THREAD

**Issue by liangzrtvjivo** [rajicon/SubAtt#1]
Hello,

While following the instructions in the README.md to Step 3, I noticed that the "train_torch_subwords.py" script references a "Subword_Torch" model class, which does not seem to be defined in the codebase.

I suspect there might be a missing class definition or a typo in the class name.

Could you please give me some advice about how to resolve this issue?

Thank you for your time and patience.

**Comment by rajicon** [comment]
Sorry, it seems I forgot to upload that file.  It is in the repository now.  I haven't gotten a chance to test the upload yet (although it should work), so please let me know if you run into more issues, or more files are missing.

**Comment by liangzrtvjivo** [comment]
The code is now running smoothly, thank you for your help and guidance!
